[project]
name = "cwog-wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ftb-snbt-lib>=0.4.1",
    "ruff>=0.15.8",
]

[dependency-groups]
dev = [
    "ruff>=0.15.8",
    "zensical>=0.0.30",
]

[tool.ruff]
line-length = 120
indent-width = 4


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D101",
    "D100",
    "RUF012",
    "D102",
    "D105",
    "S310",
]
